// <auto-generated />
namespace Hitek.GSU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addfilds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfilds));
        
        string IMigrationMetadata.Id
        {
            get { return "201510131100310_add-filds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
