// <auto-generated />
namespace Hitek.GSU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcountquestionshow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcountquestionshow));
        
        string IMigrationMetadata.Id
        {
            get { return "201511160554468_add-count-question-show"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
